logging-to-file = true
enable-magisk-update = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# you can use rvmm-config-gen to generate a config

cli-source = "inotia00/revanced-cli"
patches-source = "anddea/revanced-patches"
patches-version = "v3.6.0"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
rv-brand = "RVX anddea"
arch = "arm64-v8a"
riplib = true
build-mode = "module"
module-prop-name = "YT-RVX"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Force player buttons background' 'Hide animated button background' 'Hide double tap to like animations' 'Hide voice search button'"
excluded-patches = "'Append time stamps information' 'Custom header for YouTube' 'Spoof sreaming data' 'Custom double tap length' 'Custom package name' 'Enable wide search bar' 'Keep landscape mode' 'Layout switch' 'Translations for YouTube' 'Change player flyout panel toggles'"
# version = "19.16.39"

[Music]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
rv-brand = "RVX-Music anddea"
arch = "arm64-v8a"
riplib = true
build-mode = "module"
module-prop-name = "YTM-RVX"
included-patches = "'Custom branding icon for YouTube Music' 'Settings for YouTube Music' 'Custom branding name for YouTube Music' 'Hide voice search button'"
excluded-patches = "'Certificate spoof' 'Custom package name' 'Custom playback speed' 'Custom header for YouTube Music' 'Translations' 'Enable old player layout' 'Enable old player background' 'Enable old style miniplayer' 'Enable color match player' 'Enable zen mode'"
